<a href="https://colab.research.google.com/github/rakesh22230/Machine_Learning_Practise/blob/main/K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import sklearn.metrics as sm


df = pd.read_csv("https://raw.githubusercontent.com/rakesh22230/Machine_Learning_Practise/refs/heads/main/Iris.csv")
print(df.head())

iris = datasets.load_iris()   # only loading data
print("\n")
print (iris.data [0:5])
print("\n")
print(iris.target_names) # find the target name which is include in datasets

x = pd.DataFrame(iris.data , columns=['SL','SW','PL','PW'])  # show data as a dataframe
y = pd.DataFrame(iris.target , columns=['Target']) # show the specific column

print("\n")
print(x.head())
print("\n")
y.head()










   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


['setosa' 'versicolor' 'virginica']


    SL   SW   PL   PW
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2




Target
0       0
1       0
2       0
3       0
4       0