<a href="https://colab.research.google.com/github/rakesh22230/Machine_Learning_Practise/blob/main/Try_it.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
from collections import Counter
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Step 1: Euclidean Distance
def custom_euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# Step 2: Custom KNN Class
class CustomKNN:
    def __init__(self, k=3):
        self.k = k

    def custom_fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def custom_predict(self, X):
        return [self._custom_predict_point(x) for x in X]

    def _custom_predict_point(self, x):
        distances = [custom_euclidean_distance(x, x_train) for x_train in self.X_train]
        k_indices = np.argsort(distances)[:self.k]
        k_labels = [self.y_train[i] for i in k_indices]
        return Counter(k_labels).most_common(1)[0][0]

# Step 3: Evaluation Metrics
def custom_accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

def custom_confusion_matrix(y_true, y_pred):
    labels = np.unique(np.concatenate((y_true, y_pred)))
    cm = np.zeros((len(labels), len(labels)), dtype=int)
    for t, p in zip(y_true, y_pred):
        cm[t][p] += 1
    return cm

def custom_precision(y_true, y_pred):
    cm = custom_confusion_matrix(y_true, y_pred)
    precisions = []
    for i in range(len(cm)):
        TP = cm[i][i]
        FP = sum(cm[:, i]) - TP
        precision = TP / (TP + FP) if (TP + FP) else 0
        precisions.append(round(precision, 2))  # native Python float
    return precisions

def custom_recall(y_true, y_pred):
    cm = custom_confusion_matrix(y_true, y_pred)
    recalls = []
    for i in range(len(cm)):
        TP = cm[i][i]
        FN = sum(cm[i, :]) - TP
        recall = TP / (TP + FN) if (TP + FN) else 0
        recalls.append(round(recall, 2))
    return recalls

def custom_f1_score(y_true, y_pred):
    precisions = custom_precision(y_true, y_pred)
    recalls = custom_recall(y_true, y_pred)
    f1s = []
    for p, r in zip(precisions, recalls):
        f1 = 2 * p * r / (p + r) if (p + r) else 0
        f1s.append(round(f1, 2))
    return f1s

In [18]:
# Step 4: Load dataset
iris = load_iris()
X, y = iris.data, iris.target

# Step 5: Find best k and split ratio
best_k = 1
best_score = 0
best_split = 0.2

print("Evaluating each combination of k and split ratio...\n")
print("k\tSplit\tAccuracy")

for k in range(1, 31):
    for split in [0.2, 0.3, 0.4]:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=split, random_state=42)

        knn = CustomKNN(k=k)
        knn.custom_fit(X_train, y_train)
        preds = knn.custom_predict(X_test)
        acc = custom_accuracy(y_test, preds)

        print(f"{k}\t{split}\t{acc:.4f}")

        if acc > best_score:
            best_score = acc
            best_k = k
            best_split = split

# Step 6: Final Evaluation with best k and split
print("\nBest K found:", best_k, "| Best Split Ratio:", best_split, "| Best Accuracy:", round(best_score, 4))


Evaluating each combination of k and split ratio...

k	Split	Accuracy
1	0.2	1.0000
1	0.3	1.0000
1	0.4	0.9833
2	0.2	1.0000
2	0.3	1.0000
2	0.4	0.9833
3	0.2	1.0000
3	0.3	1.0000
3	0.4	0.9833
4	0.2	1.0000
4	0.3	1.0000
4	0.4	0.9833
5	0.2	1.0000
5	0.3	1.0000
5	0.4	0.9833
6	0.2	1.0000
6	0.3	1.0000
6	0.4	0.9833
7	0.2	0.9667
7	0.3	1.0000
7	0.4	0.9833
8	0.2	1.0000
8	0.3	1.0000
8	0.4	0.9833
9	0.2	1.0000
9	0.3	1.0000
9	0.4	0.9833
10	0.2	1.0000
10	0.3	1.0000
10	0.4	0.9833
11	0.2	1.0000
11	0.3	1.0000
11	0.4	1.0000
12	0.2	1.0000
12	0.3	1.0000
12	0.4	1.0000
13	0.2	1.0000
13	0.3	1.0000
13	0.4	1.0000
14	0.2	1.0000
14	0.3	1.0000
14	0.4	1.0000
15	0.2	1.0000
15	0.3	1.0000
15	0.4	1.0000
16	0.2	1.0000
16	0.3	1.0000
16	0.4	1.0000
17	0.2	1.0000
17	0.3	1.0000
17	0.4	1.0000
18	0.2	1.0000
18	0.3	1.0000
18	0.4	1.0000
19	0.2	1.0000
19	0.3	1.0000
19	0.4	1.0000
20	0.2	1.0000
20	0.3	1.0000
20	0.4	1.0000
21	0.2	1.0000
21	0.3	1.0000
21	0.4	1.0000
22	0.2	1.0000
22	0.3	1.0000
22	0.4	0.9833
23	0.2	1.0000
23	0.3	1.0000
23	0.

In [20]:
# Final Evaluation using best_k and best_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=best_split, random_state=42)

# Use your custom KNN model
model = CustomKNN(k=best_k)
model.custom_fit(X_train, y_train)
predictions = model.custom_predict(X_test)

# Print evaluation results
print("\nCustom KNN Evaluation:")
print("Accuracy:", custom_accuracy(y_test, predictions))
print("Confusion Matrix:\n", custom_confusion_matrix(y_test, predictions))

# Calculate metrics
precision = custom_precision(y_test, predictions)
recall = custom_recall(y_test, predictions)
f1 = custom_f1_score(y_test, predictions)

print("Precision:", [float(p) for p in precision])
print("Recall:", [float(r) for r in recall])
print("F1-score:", [float(f) for f in f1])




Custom KNN Evaluation:
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Precision: [1.0, 1.0, 1.0]
Recall: [1.0, 1.0, 1.0]
F1-score: [1.0, 1.0, 1.0]


In [28]:
# ====== Step 1: Import libraries ======
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score


# ====== Step 3: Set best k and split ======
best_k = 5
best_split = 0.2

# ====== Step 4: Split data ======
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=best_split, random_state=42)

# ====== Step 5: Train model ======
model = KNeighborsClassifier(n_neighbors=best_k)
model.fit(X_train, y_train)

# ====== Step 6: Predict ======
y_pred = model.predict(X_test)

# ====== Step 7: Evaluate ======
print("\n--- Built-in KNN Evaluation ---")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average=None))
print("Recall:", recall_score(y_test, y_pred, average=None))
print("F1-score:", f1_score(y_test, y_pred, average=None))



--- Built-in KNN Evaluation ---
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Precision: [1. 1. 1.]
Recall: [1. 1. 1.]
F1-score: [1. 1. 1.]
